theme:
  name: material
  logo:
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
site_name: Shihao Xia
nav:
  - Home: index.md
  - Projects:
    - AICourt:
      - projects/aicourt/index.md
    - Turtle Soup:  
      - projects/turtlesoup/index.md
      - projects/turtlesoup/privacy.md
    - Instago:
      - projects/instago/index.md
    - Jarvis: 
      - projects/jarvis/index.md
    - Softlife: 
      - projects/softlife/index.md
    - Secretary:
      - projects/secretary/index.md
      - projects/secretary/privacy.md
  
  - Blog:
    - blog/index.md 
plugins:
  - blog:
      categories_allowed:
  - search